CREATE TABLE STUDENTS(
REG_ID INT  NOT NULL,
NAME VARCHAR(20) NOT NULL,
ADDRESS CHAR(25) NOT NULL,
CITY CHAR (25) NOT NULL,

PRIMARY KEY(REG_ID)
);

CREATE TABLE SUBJECTS(
COD_SUBJ INT  NOT NULL,
NAME_SUBJ VARCHAR(20) NOT NULL,
WORKLOAD INT NOT NULL,

PRIMARY KEY(COD_SUBJ)
);

ALTER TABLE SUBJECTS MODIFY COD_SUBJ VARCHAR(5) NOT NULL;

CREATE TABLE TEACHERS(
COD_TEACHER INT  NOT NULL,
NAME VARCHAR(20) NOT NULL,
ADDRESS VARCHAR(20) NOT NULL,
CITY VARCHAR(20) NOT NULL,

PRIMARY KEY(COD_TEACHER)

);

CREATE TABLE CLASS(

COD_SUBJECT INT  NOT NULL,
COD_CLASS INT NOT NULL,
COD_TEACHERS INT NOT NULL,
YEAR INT NOT NULL,
HOURS  VARCHAR(20) NOT NULL,

PRIMARY KEY(COD_SUBJECT, COD_CLASS, COD_TEACHERS, YEAR),
FOREIGN KEY (COD_SUBJECT) REFERENCES SUBJECTS(COD_SUBJ),
FOREIGN KEY (COD_TEACHERS) REFERENCES TEACHERS(COD_TEACHER)

);

CREATE TABLE SCHOOL_RECORDS(

REG_ID INT  NOT NULL,
COD_SUBJ INT  NOT NULL,
COD_CLASS INT NOT NULL,
COD_TEACHER INT NOT NULL,
YEAR INT NOT NULL,
ATTENDANCE INT NOT NULL,
GRADE INT NOT NULL,

PRIMARY KEY(REG_ID, COD_SUBJ,COD_CLASS,COD_TEACHER, YEAR)


);
ALTER TABLE SCHOOL_RECORDS
ADD FOREIGN KEY(REG_ID) REFERENCES STUDENTS(REG_ID);

ALTER TABLE SCHOOL_RECORDS
ADD FOREIGN KEY (COD_SUBJ) REFERENCES CLASS(COD_SUBJECT);

ALTER TABLE SCHOOL_RECORDS
ADD FOREIGN KEY (COD_CLASS) REFERENCES CLASS(COD_CLASS);

ALTER TABLE SCHOOL_RECORDS
ADD FOREIGN KEY (COD_TEACHER) REFERENCES CLASS(COD_TEACHERS);

ALTER TABLE SCHOOL_RECORDS
ADD FOREIGN KEY (YEAR) REFERENCES CLASS(YEAR);


DROP TABLE SCHOOL_RECORDS;
DROP TABLE CLASS;

